name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Clone the submodules
      run: git reset --hard HEAD && git clean -xfd && git submodule sync --recursive && git submodule update --recursive --init
    - name: Build Application
      run: make ci
